/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FDialog: typeof import('./components/FDialog.vue')['default']
    FTable: typeof import('./components/FTable/index.vue')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFemale: typeof import('~icons/ep/female')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMale: typeof import('~icons/ep/male')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ElAside: (typeof import('element-plus/es'))['ElAside'];
  const ElAvatar: (typeof import('element-plus/es'))['ElAvatar'];
  const ElButton: (typeof import('element-plus/es'))['ElButton'];
  const ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
  const ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
  const ElContainer: (typeof import('element-plus/es'))['ElContainer'];
  const ElDialog: (typeof import('element-plus/es'))['ElDialog'];
  const ElForm: (typeof import('element-plus/es'))['ElForm'];
  const ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
  const ElHeader: (typeof import('element-plus/es'))['ElHeader'];
  const ElIcon: (typeof import('element-plus/es'))['ElIcon'];
  const ElImage: (typeof import('element-plus/es'))['ElImage'];
  const ElInput: (typeof import('element-plus/es'))['ElInput'];
  const ElMain: (typeof import('element-plus/es'))['ElMain'];
  const ElMenu: (typeof import('element-plus/es'))['ElMenu'];
  const ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
  const ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup'];
  const ElPagination: (typeof import('element-plus/es'))['ElPagination'];
  const ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton'];
  const ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup'];
  const ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar'];
  const ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu'];
  const ElTable: (typeof import('element-plus/es'))['ElTable'];
  const ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
  const ElTag: (typeof import('element-plus/es'))['ElTag'];
  const FDialog: (typeof import('./components/FDialog.vue'))['default'];
  const FTable: (typeof import('./components/FTable/index.vue'))['default'];
  const IEpExpand: (typeof import('~icons/ep/expand'))['default'];
  const IEpFemale: (typeof import('~icons/ep/female'))['default'];
  const IEpFold: (typeof import('~icons/ep/fold'))['default'];
  const IEpLock: (typeof import('~icons/ep/lock'))['default'];
  const IEpMale: (typeof import('~icons/ep/male'))['default'];
  const IEpUser: (typeof import('~icons/ep/user'))['default'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
}
