// Auto-generated by vite-plugin-typed-env. DO NOT EDIT.
// Re-run vite to regenerate this file.

/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly VITE_PORT: number;
  readonly VITE_AXIOS_TIME_OUT: number;
  readonly VITE_AXIOS_BASE_URL: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
