name: 打包和部署 vue-app

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

env: 
  TARGET: /www/wwwroot/nestjs-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装pnpm
        uses: pnpm/action-setup@v4
        with: 
          version: 10.26.0
      
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          # cache: 'pnpm'
      
      - name: 缓存 pnpm store
        uses: actions/cache@v4
        with: 
          path: ~/local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      
      - name: ts类型检查
        run: npx vue-tsc --noEmit

      - name: 打包
        run: pnpm run build

      - name: 部署到腾讯云
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: 'dist/*'
          target: ${{ env.TARGET }}
          strip_components: 1
          rm: true
      
      - name: 部署成功通知
        run: echo "☑️部署成功！时间：$(date +'%Y-%m-%d %h:%M:%S')" 
